// Address Presentation Providers
// Phase 6: Wrapper providers for easy UI consumption
//
// These providers wrap the Application Layer Notifiers and provide
// convenient access patterns for UI components.

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'notifiers/address_notifier.dart';
import '../../domain/entities/address_entity.dart';

// Re-export the Notifier providers from Application layer
//
// Usage in UI:
// ```dart
// // Watch state
// final addressState = ref.watch(addressProvider);
//
// // Call methods
// final notifier = ref.read(addressProvider.notifier);
// notifier.loadAddresses(userId);
// ```

// ========================================
// ADDRESS NOTIFIER PROVIDER (re-export)
// ========================================
// addressProvider is auto-generated by Riverpod from AddressNotifier

// ========================================
// CONVENIENCE PROVIDERS
// ========================================

/// Provider for addresses list state
final addressesListProvider = Provider<AsyncValue<List<AddressEntity>>>((ref) {
  final addressState = ref.watch(addressProvider);
  return addressState.addresses;
});

/// Provider for primary address state
final primaryAddressProvider = Provider<AsyncValue<AddressEntity?>>((ref) {
  final addressState = ref.watch(addressProvider);
  return addressState.primaryAddress;
});

/// Provider for address loading state
final isAddressLoadingProvider = Provider<bool>((ref) {
  final addressState = ref.watch(addressProvider);
  return addressState.isSaving || addressState.isDeleting;
});

/// Provider for address error message
final addressErrorProvider = Provider<String?>((ref) {
  final addressState = ref.watch(addressProvider);
  return addressState.errorMessage;
});

/// Provider for address count
/// Returns the count of loaded addresses (0 if loading or error)
final addressCountProvider = Provider<int>((ref) {
  final addressState = ref.watch(addressProvider);
  return addressState.addresses.when(
    data: (addresses) => addresses.length,
    loading: () => 0,
    error: (_, _) => 0,
  );
});
