// Content Repository Implementation
// Implements ContentRepository dari domain layer menggunakan API datasource

import 'package:dio/dio.dart';
import 'package:labuda/core/api/api.dart';
import 'package:labuda/domains/social/content/data/mappers/content_mapper.dart';
import 'package:labuda/domains/social/content/data/remote/content_api_datasource.dart';
import 'package:labuda/domains/social/content/domain/entities/content.dart';
import 'package:labuda/domains/social/content/domain/repositories/content_repository.dart';

/// Content Repository Implementation
///
/// CONTRACT ALIGNMENT V1:
/// - Uses unified ContentStatus (active, deleted)
/// - RequestStatus removed - uses canonical ContentStatus instead
/// - Content resource_projection is the canonical linked-content shape
///
/// Menggunakan ContentApiDatasource untuk HTTP operations.
/// Menghandle error mapping dari ApiException ke domain error.
class ContentRepositoryImpl implements ContentRepository {
  final ContentApiDatasource _datasource;
  final ApiClient _apiClient;

  ContentRepositoryImpl(this._datasource, this._apiClient);

  // ==========================================================================
  // Error Handling Helper
  // ==========================================================================

  String _mapDioError(DioException e) {
    final exception = _apiClient.extractException(e);
    return exception.message;
  }

  // ==========================================================================
  // CRUD Operations
  // ==========================================================================

  @override
  Future<ContentRepositoryResult<Content>> createContent({
    required String authorId,
    String? authorUsername,
    String? authorAvatarUrl,
    required String content,
    List<MediaEntity> media = const [],
    List<String> tags = const [],
    List<String> taggedUsers = const [],
    ContentSettings settings = const ContentSettings(),
    ContentLocation? location,
  }) async {
    try {
      final entity = Content(
        id: '', // Will be generated by backend
        content: content,
        authorId: authorId,
        authorUsername: authorUsername,
        authorAvatarUrl: authorAvatarUrl,
        status: ContentStatus.active, // All content starts as active
        media: media,
        tags: tags,
        taggedUsers: taggedUsers,
        mentionedUserIds: [],
        settings: settings,
        location: location,
        engagement: const ContentEngagement(),
        moderationInfo: const ContentModerationInfo(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final dto = ContentMapper.toCreateDto(entity);
      final response = await _datasource.createContent(dto);
      final result = ContentMapper.toEntity(response);

      return ContentRepositoryResult.success(result);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to create content: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<Content>> getContentById(
    String contentId,
  ) async {
    try {
      final response = await _datasource.getContentById(contentId);
      final entity = ContentMapper.toEntity(response);
      return ContentRepositoryResult.success(entity);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to get content: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<List<Content>>> getContentsByAuthor(
    String authorId, {
    int? limit,
    int? offset,
  }) async {
    try {
      // Delegates to cursor-paginated datasource; offset is not forwarded
      // (no backend support). Always fetches the first page.
      final page = await _datasource.getUserContents(
        authorId,
        limit: limit ?? 20,
      );
      return ContentRepositoryResult.success(
        ContentMapper.toEntityList(page.data),
      );
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to get author contents: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<ContentAuthorPage>> getContentsByAuthorPaged(
    String authorId, {
    int limit = 20,
    String? cursor,
  }) async {
    try {
      final page = await _datasource.getUserContents(
        authorId,
        limit: limit,
        cursor: cursor,
      );
      return ContentRepositoryResult.success(
        ContentAuthorPage(
          items: ContentMapper.toEntityList(page.data),
          nextCursor: page.nextCursor,
          hasMore: page.hasMore,
        ),
      );
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to get author contents: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<List<Content>>> getContents({
    int? limit,
    int? offset,
    String? location,
    ContentStatus? status,
  }) async {
    try {
      final response = await _datasource.getContents(
        status: status != null ? _mapStatus(status) : 'active',
        city: location,
        limit: limit,
        offset: offset,
      );
      final entities = ContentMapper.toEntityList(response);
      return ContentRepositoryResult.success(entities);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to get contents: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<Content>> updateContent(
    String contentId,
    Content content,
  ) async {
    try {
      final dto = ContentMapper.toUpdateDto(content);
      final response = await _datasource.updateContent(contentId, dto);
      final entity = ContentMapper.toEntity(response);
      return ContentRepositoryResult.success(entity);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to update content: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<void>> deleteContent(String contentId) async {
    try {
      await _datasource.deleteContent(contentId);
      return ContentRepositoryResult.success(null);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to delete content: $e');
    }
  }

  // ==========================================================================
  // Feed & Discovery
  // ==========================================================================

  @override
  Future<ContentRepositoryResult<ContentSearchResult>> searchContents({
    required String query,
    int? limit,
    int? offset,
    String? location,
  }) async {
    try {
      final response = await _datasource.searchContents(
        query,
        city: location,
        limit: limit,
        offset: offset,
      );
      final result = ContentMapper.toSearchResult(response);
      return ContentRepositoryResult.success(result);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error('Failed to search contents: $e');
    }
  }

  @override
  Future<ContentRepositoryResult<List<Content>>> getTrendingContents({
    int? limit,
  }) async {
    try {
      final response = await _datasource.getTrendingContents(limit: limit);
      final entities = ContentMapper.toEntityList(response);
      return ContentRepositoryResult.success(entities);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error(
        'Failed to get trending contents: $e',
      );
    }
  }

  @override
  Future<ContentRepositoryResult<List<Content>>> getContentsByLocation({
    required String location,
    int? limit,
  }) async {
    try {
      final response = await _datasource.getContents(
        city: location,
        limit: limit,
        status: 'active',
      );
      final entities = ContentMapper.toEntityList(response);
      return ContentRepositoryResult.success(entities);
    } on DioException catch (e) {
      return ContentRepositoryResult.error(_mapDioError(e));
    } catch (e) {
      return ContentRepositoryResult.error(
        'Failed to get contents by location: $e',
      );
    }
  }

  // getFeed() removed (BATCH C2): ContentRepository no longer provides feed.
  // For social timeline, use Home/Feed domain's FeedApiDatasource instead.

  // ==========================================================================
  // Engagement
  // ==========================================================================

  // Note: View tracking is handled by backend automatically via GET /content/contents/:id
  // No explicit incrementViewCount needed

  // ==========================================================================
  // Helper Methods - Canonical Status Mapping
  // ==========================================================================

  /// Map ContentStatus to backend API status string
  ///
  /// CONTRACT: Only canonical status values are sent to backend
  String _mapStatus(ContentStatus status) {
    return switch (status) {
      ContentStatus.active => 'active',
      ContentStatus.deleted => 'deleted',
    };
  }
}
