/// Chat Presentation Providers - Presentation layer providers for Chat feature
///
/// This file provides presentation-specific providers that depend on data layer
/// and core providers. No GetIt/ServiceLocator usage.
///
/// MIGRATION STATUS: Fully migrated from sl<> to Riverpod
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';
// R4.2: Import currentUserIdProvider directly instead of mega-barrel
import 'package:labuda/shared/providers/auth_status_providers.dart'
    show currentUserIdProvider;
import 'package:labuda/domains/chat/chat/presentation/providers/chat_notifier.dart';
import 'package:labuda/domains/chat/chat/presentation/providers/chat_state.dart';
import 'package:labuda/domains/chat/chat/presentation/utils/chat_identity_display.dart';

// Export generated providers for easy access
// These are generated by build_runner from chat_notifier.dart
export 'package:labuda/domains/chat/chat/presentation/providers/chat_notifier.dart';

// Re-export data layer providers
export 'package:labuda/domains/chat/chat/data/chat_providers.dart'
    show chatRepositoryProvider, chatRoomEventsProvider;

// ========================================
// Current User ID Provider
// ========================================
// NOTE: Using official currentUserIdProvider from shared/providers
// No feature-specific wrapper needed - auth is a core concern

// ========================================
// Application Layer Providers (Notifiers)
// ========================================
// NOTE: The following providers are now generated by build_runner
// from chat_notifier.dart using @riverpod annotations:
// - chatListProvider (was chatListNotifierProvider)
// - chatDetailProvider (was chatDetailNotifierProvider) - family provider
// - unreadCountProvider (was unreadCountNotifierProvider)
// - presenceProvider (was presenceNotifierProvider)
//
// Usage: ref.watch(chatDetailProvider(chatId))

// ========================================
// Computed Providers
// ========================================

/// Total Unread Count Provider
final totalUnreadCountProvider = Provider<int>((ref) {
  final currentUserId = ref.watch(currentUserIdProvider);
  final chatListState = ref.watch(chatListProvider);
  return chatListState.chats.fold<int>(
    0,
    (sum, chat) => sum + chat.getUnreadCount(currentUserId),
  );
});

/// Chat List with Unread Counts Provider
final chatListWithUnreadProvider = Provider<ChatListState>((ref) {
  final chatListState = ref.watch(chatListProvider);
  return chatListState;
});

// ========================================
// Feature Flag Providers
// ========================================

final typingIndicatorEnabledProvider = Provider<bool>((ref) => false);
final readReceiptEnabledProvider = Provider<bool>((ref) => true);
// Backend has no presence endpoints. presenceProvider.isUserOnline() always
// returns false. This flag is false to match reality.
final presenceEnabledProvider = Provider<bool>((ref) => false);

// ========================================
// Helper Providers
// ========================================

/// Get Other Participant ID Provider
final otherParticipantIdProvider = Provider.family<String?, String>((
  ref,
  chatId,
) {
  final chatDetailState = ref.watch(chatDetailProvider(chatId));
  final currentUserId = ref.watch(currentUserIdProvider);

  final chat = chatDetailState.chat;
  if (chat == null || chat.participantIds.length != 2) {
    return null;
  }

  return chat.getOtherParticipantId(currentUserId);
});

/// Get Other Participant Name Provider
final otherParticipantNameProvider = Provider.family<String, String>((
  ref,
  chatId,
) {
  final chatDetailState = ref.watch(chatDetailProvider(chatId));
  final currentUserId = ref.watch(currentUserIdProvider);

  final chat = chatDetailState.chat;
  if (chat == null) {
    return 'Unknown';
  }

  return formatChatHandle(chat.getOtherParticipantName(currentUserId));
});
