package entity

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// DeliveryEventType is the canonical delivery measurement vocabulary. Each
// value names EXACTLY what happened — never more.
type DeliveryEventType string

const (
	// EventTypeIncluded records a server-side observation: the canonical
	// promotion card was placed in the feed response actually returned to a
	// viewer (after slot policy and interleave). Every included observation
	// carries a server-issued exposure identity (ExposureID) returned to the
	// client with that card.
	EventTypeIncluded DeliveryEventType = "included"

	// EventTypeImpression records a client-explicit acknowledgement: the
	// client echoed the issued exposure identity back, proving the canonical
	// card was actually exposed/rendered. It is NEVER created by the server
	// on its own — without the echoed exposure identity there is no
	// impression.
	EventTypeImpression DeliveryEventType = "impression"

	// EventTypeClick records a client-explicit acknowledgement of an explicit
	// user tap on the canonical card, echoing the issued exposure identity.
	// It is NEVER created by the server on its own and never inferred from
	// inclusion, impression, selection, or navigation — a click is only ever
	// the explicit user action the client reports.
	EventTypeClick DeliveryEventType = "click"
)

// DeliveryEvent is one immutable canonical delivery measurement observation.
//
// Attribution: every event resolves to the CANONICAL contract id
// (promotion_contracts.id) — never a legacy promotion_instance id nor the
// purged competing promotions aggregate.
//
// ExposureID is the canonical exposure identity:
//   - on an 'included' event: the server-issued token handed to the client
//     with the card (the only proof that a delivery actually presented the
//     promotion);
//   - on an 'impression' / 'click' event: the echoed token from the
//     acknowledgement.
//
// No lifecycle state is duplicated here: status, activation, funding,
// eligibility, and operability are NOT part of the event.
type DeliveryEvent struct {
	ID               uuid.UUID
	ContractID       uuid.UUID // canonical authority: promotion_contracts.id
	TargetType       string
	TargetID         uuid.UUID
	ViewerID         uuid.UUID
	EventType        DeliveryEventType
	ExposureID       uuid.UUID
	ServerOccurredAt time.Time // DB clock (server time authority)
	CreatedAt        time.Time
}

// NewIncludedEvent constructs an 'included' observation: the promotion card
// entered a feed response, and the server issues a fresh exposure identity
// (exposureID, generated by the measurement authority) for the client to
// acknowledge later.
func NewIncludedEvent(contractID uuid.UUID, targetType string, targetID uuid.UUID, viewerID uuid.UUID, exposureID uuid.UUID, now time.Time) (*DeliveryEvent, error) {
	return newDeliveryEvent(EventTypeIncluded, contractID, targetType, targetID, viewerID, exposureID, now)
}

// NewImpressionEvent constructs an 'impression' observation from a client
// acknowledgement: exposureID is the echoed token of a previously issued
// 'included' event. The server NEVER fabricates this on its own.
func NewImpressionEvent(contractID uuid.UUID, targetType string, targetID uuid.UUID, viewerID uuid.UUID, exposureID uuid.UUID, now time.Time) (*DeliveryEvent, error) {
	return newDeliveryEvent(EventTypeImpression, contractID, targetType, targetID, viewerID, exposureID, now)
}

// NewClickEvent constructs a 'click' observation from a client
// acknowledgement: exposureID is the echoed token of a previously issued
// 'included' event, and the promotion identity comes from that issued event
// (never from the client). The server NEVER fabricates this on its own.
func NewClickEvent(contractID uuid.UUID, targetType string, targetID uuid.UUID, viewerID uuid.UUID, exposureID uuid.UUID, now time.Time) (*DeliveryEvent, error) {
	return newDeliveryEvent(EventTypeClick, contractID, targetType, targetID, viewerID, exposureID, now)
}

func newDeliveryEvent(eventType DeliveryEventType, contractID uuid.UUID, targetType string, targetID uuid.UUID, viewerID uuid.UUID, exposureID uuid.UUID, now time.Time) (*DeliveryEvent, error) {
	if contractID == uuid.Nil {
		return nil, fmt.Errorf("delivery event: contract_id required")
	}
	if targetType == "" {
		return nil, fmt.Errorf("delivery event: target_type required")
	}
	if targetID == uuid.Nil {
		return nil, fmt.Errorf("delivery event: target_id required")
	}
	if viewerID == uuid.Nil {
		return nil, fmt.Errorf("delivery event: viewer_id required")
	}
	if exposureID == uuid.Nil {
		return nil, fmt.Errorf("delivery event: exposure_id required")
	}
	switch eventType {
	case EventTypeIncluded, EventTypeImpression, EventTypeClick:
	default:
		return nil, fmt.Errorf("delivery event: unknown event type %q", string(eventType))
	}
	return &DeliveryEvent{
		ID:               uuid.New(),
		ContractID:       contractID,
		TargetType:       targetType,
		TargetID:         targetID,
		ViewerID:         viewerID,
		EventType:        eventType,
		ExposureID:       exposureID,
		ServerOccurredAt: now,
		CreatedAt:        now,
	}, nil
}

// DeliveryAnalytics is the truthful seller-facing projection of delivery
// measurement events for one contract. It is a projection only — never a
// financial authority (the ledger owns money truth).
type DeliveryAnalytics struct {
	ContractID     uuid.UUID
	IncludedCount  int
	ImpressionCount int
	ClickCount     int
}