package models

import (
	"time"

	"github.com/google/uuid"
)

// OutboxStatus represents the possible states of an outbox message.
type OutboxStatus string

const (
	// OutboxStatusPending means the message is waiting to be processed.
	OutboxStatusPending OutboxStatus = "pending"
	// OutboxStatusProcessing means the message is currently being processed by a worker.
	OutboxStatusProcessing OutboxStatus = "processing"
	// OutboxStatusSucceeded means the message was successfully delivered.
	OutboxStatusSucceeded OutboxStatus = "succeeded"
	// OutboxStatusFailed means the message failed and will be retried.
	OutboxStatusFailed OutboxStatus = "failed"
	// OutboxStatusDeadLetter means the message exceeded max retries and will not be retried.
	OutboxStatusDeadLetter OutboxStatus = "dead_letter"
)

// OutboxMessageDB represents the outbox table.
//
// This is the generic, reusable outbox pattern implementation for reliable event delivery.
// Events are persisted in the same transaction as the domain state change, then processed
// by background workers with proper locking and retry semantics.
//
// FINAL SCHEMA - All columns aligned with database table `outbox`
// No backward compatibility - this is the authoritative schema.
//
// IDEMPOTENCY:
// - idempotency_key field for business-level deduplication
// - UNIQUE constraint ensures only one message with that key exists
// - Workers can safely retry processing without side effects
type OutboxMessageDB struct {
	// Primary key - UUID generated by database
	ID uuid.UUID `json:"id"`

	// Aggregate identification - what domain entity this event relates to
	AggregateType string `json:"aggregate_type"` // e.g., "payment", "order", "user"
	AggregateID   uuid.UUID `json:"aggregate_id"`

	// Event identification - what type of event occurred
	EventType string `json:"event_type"` // e.g., "payment.completed", "order.created"

	// Event payload - JSON data to be delivered
	Payload map[string]interface{} `json:"payload"`

	// Processing status - see OutboxStatus constants
	Status OutboxStatus `json:"status"`

	// Retry tracking
	RetryCount    int       `json:"retry_count"`              // Number of processing attempts made
	NextAttemptAt time.Time `json:"next_attempt_at"` // When to retry

	// Business-level idempotency key
	// UNIQUE constraint ensures only one message with this key exists
	IdempotencyKey string `json:"idempotency_key"`

	// Audit timestamps
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TableName specifies the table name for OutboxMessageDB.
func (OutboxMessageDB) TableName() string {
	return "outbox"
}

// NeedsRetry returns true if the message should be retried.
func (o *OutboxMessageDB) NeedsRetry() bool {
	return o.Status == OutboxStatusPending || o.Status == OutboxStatusFailed
}

// IsReadyForProcessing returns true if the message is due for processing.
func (o *OutboxMessageDB) IsReadyForProcessing() bool {
	return o.NeedsRetry() && time.Now().After(o.NextAttemptAt)
}


