// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// HiShumi Firebase configuration
/// Generated from Firebase project hishumi (number 1079914053843)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFh1qC615YFLWS2QjozXMrxtWD-Ts_6o',
    appId: '1:1079914053843:web:e1fd2850ed519a5fe15426',
    messagingSenderId: '1079914053843',
    projectId: 'hishumi',
    authDomain: 'hishumi.firebaseapp.com',
    storageBucket: 'hishumi.firebasestorage.app',
    measurementId: 'G-8P59DL46RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaEOGP1Plca56W9LSVPpiawF4lWbU_3xg',
    appId: '1:1079914053843:android:c3b70fa71634c2f8e15426',
    messagingSenderId: '1079914053843',
    projectId: 'hishumi',
    storageBucket: 'hishumi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbml4CB04FVUj3fsQjZn3rSUdNXQGRRM',
    appId: '1:1079914053843:ios:1399ad098cdce6c2e15426',
    messagingSenderId: '1079914053843',
    projectId: 'hishumi',
    storageBucket: 'hishumi.firebasestorage.app',
    iosBundleId: 'com.hishumi.app',
  );

}
