// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// LABUDA Firebase configuration
/// Generated from Firebase Console - labuda-79de2
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSSTsciRZw7DvCR_2QUoz3FB82GnCKeA',
    appId: '1:883544146901:web:9d14717d7f9e5a5cfaf35c',
    messagingSenderId: '883544146901',
    projectId: 'labuda-79de2',
    authDomain: 'labuda-79de2.firebaseapp.com',
    storageBucket: 'labuda-79de2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSSTsciRZw7DvCR_2QUoz3FB82GnCKeA',
    appId: '1:883544146901:android:9d14717d7f9e5a5cfaf35c',
    messagingSenderId: '883544146901',
    projectId: 'labuda-79de2',
    storageBucket: 'labuda-79de2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMgnWF-YnyYxF1_Ha3THszw8DJ7h7Yik',
    appId: '1:883544146901:ios:33b4631274b2eb26faf35c',
    messagingSenderId: '883544146901',
    projectId: 'labuda-79de2',
    storageBucket: 'labuda-79de2.firebasestorage.app',
    iosBundleId: 'com.labuda.app.labuda',
  );

}
