import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:labuda/core/core.dart';
import 'package:labuda/domains/social/comment/data/comment_repository_impl.dart';
import 'package:labuda/domains/social/comment/data/remote/comment_api_datasource.dart';
import 'package:labuda/domains/social/comment/domain/repositories/comment_repository.dart';
import 'package:labuda/domains/social/comment/domain/usecases/validate_comment_content_use_case.dart';

/// ========================================
/// Riverpod Providers for Comment Module
/// ========================================
/// MIGRATION STATUS: Now using pure Riverpod - no ServiceLocator
/// Core dependencies from core/providers/core_providers.dart

/// CommentApiDatasource Provider
final commentApiDatasourceProvider = Provider<CommentApiDatasource>((ref) {
  final apiClient = ref.watch(apiClientProvider);
  final logger = ref.watch(loggerServiceProvider);
  return CommentApiDatasource(apiClient, logger: logger);
});

/// CommentRepository Provider
final commentRepositoryProvider = Provider<CommentRepository>((ref) {
  final datasource = ref.watch(commentApiDatasourceProvider);
  final logger = ref.watch(loggerServiceProvider);
  return CommentRepositoryImpl(datasource, logger: logger);
});

/// INotificationTrigger Provider (from core)
/// Uses coreNotificationTriggerProvider which returns null if not registered
final notificationTriggerProvider = Provider<INotificationTrigger?>((ref) {
  return ref.watch(coreNotificationTriggerProvider);
});

/// CommentNotifier Provider is auto-generated by @riverpod annotation
/// See comment_notifier.g.dart for the generated provider
///
/// NOTE: There is no commentCountProvider. The only live comment-count
/// authority is `content.engagement.commentCount` (detailed on the content
/// detail surface); the legacy page-total count path was removed.

// =============================================================================
// USECASE PROVIDERS
// =============================================================================

/// Validate Comment Content UseCase Provider
final validateCommentContentUseCaseProvider =
    Provider<ValidateCommentContentUseCase>((ref) {
      final repository = ref.watch(commentRepositoryProvider);
      return ValidateCommentContentUseCase(repository);
    });
