package capability

import "strings"

// ============================================================
// DERIVED CATALOG
// ============================================================
//
// The catalog is DERIVED, never hand-maintained. It is generated by walking
// the canonical universe (canonicalCapabilities in capability.go), so a new
// capability constant added to the universe automatically appears here — in
// the governance API, in the admin dashboard, and in derived full access.
//
// There is exactly ONE source of truth for "which capabilities exist":
// the canonical universe. Category, description and criticality are
// presentation metadata layered on top of it, and every one of them has a
// deterministic fallback so a capability can never silently disappear from
// the dashboard because someone forgot to update a second list.

// Descriptor is the governance-facing description of one canonical capability.
type Descriptor struct {
	// Capability is the capability string (e.g. "finance.withdraw.read").
	Capability string `json:"capability"`

	// Category is the capability cluster used for UI grouping (e.g. "Finance").
	//
	// Derived from the first dot-segment of the capability, so every cluster
	// present in the universe is always surfaced. No cluster can be hidden by
	// a missing grouping entry.
	Category string `json:"category"`

	// Description is a human-readable description. Falls back to a derived
	// label when no curated description exists.
	Description string `json:"description"`

	// Critical marks capabilities that must not be revoked casually.
	Critical bool `json:"critical"`
}

// Catalog returns the canonical capability catalog as UI descriptors.
//
// Ordering follows the canonical universe for a stable, deterministic
// presentation. The returned list always covers the universe exactly.
func Catalog() []Descriptor {
	out := make([]Descriptor, 0, len(canonicalCapabilities))
	for _, c := range canonicalCapabilities {
		out = append(out, Descriptor{
			Capability:  c.String(),
			Category:    Category(c),
			Description: Describe(c),
			Critical:    IsCritical(c),
		})
	}
	return out
}

// Category returns the canonical UI cluster of a capability.
//
// Derived from the first dot-segment of the capability string. Unknown
// clusters are title-cased verbatim rather than dropped, so the catalog can
// never silently omit a cluster.
func Category(c Capability) string {
	raw := c.String()
	if raw == "" {
		return "Other"
	}
	cluster := raw
	if idx := strings.Index(raw, "."); idx > 0 {
		cluster = raw[:idx]
	}
	if cluster == "" {
		return "Other"
	}
	return strings.ToUpper(cluster[:1]) + cluster[1:]
}

// Describe returns the human-readable description of a capability.
//
// Curated descriptions are optional enrichment. When none exists, a
// deterministic label is derived from the capability string itself, so a newly
// added capability is still fully surfaced without editing a second list.
func Describe(c Capability) string {
	if d, ok := curatedDescriptions[c]; ok {
		return d
	}
	return derivedDescription(c)
}

// derivedDescription turns "promotion.campaign.stop" into
// "Can stop promotion campaign".
func derivedDescription(c Capability) string {
	parts := strings.Split(c.String(), ".")
	if len(parts) == 0 {
		return c.String()
	}
	pretty := func(s string) string {
		return strings.ReplaceAll(s, "_", " ")
	}
	action := pretty(parts[len(parts)-1])
	resource := make([]string, 0, len(parts)-1)
	for _, p := range parts[:len(parts)-1] {
		resource = append(resource, pretty(p))
	}
	if len(resource) == 0 {
		return "Can " + action
	}
	return "Can " + action + " " + strings.Join(resource, " ")
}

// criticalCapabilities is the canonical set of high-impact capabilities.
// It is keyed by capability so membership cannot drift by position.
var criticalCapabilities = map[Capability]bool{
	CapFinanceWithdrawReview:         true,
	CapFinanceDisputeResolve:         true,
	CapFinancePaymentMethodManage:    true,
	CapGovernanceUserSuspend:         true,
	CapGovernanceUserBan:             true,
	CapGovernanceUserActivate:        true,
	CapGovernanceUserUnban:           true,
	CapGovernanceRoleAssign:          true,
	CapGovernanceCapabilityAssign:    true,
	CapModerationContentRemove:       true,
	CapModerationCaseResolve:         true,
	CapModerationEvidenceRead:        true,
	CapModerationAppealReview:        true,
	CapPromotionExternalProductReview: true,
	CapConfigUpdateGeneral:           true,
	CapConfigUpdateFinancial:         true,
}

// IsCritical reports whether a capability is high-impact.
//
// This is the ONE canonical criticality authority. Handlers and services must
// consult this function rather than carrying their own switch or list.
func IsCritical(c Capability) bool {
	return criticalCapabilities[c]
}

// curatedDescriptions are optional human-written descriptions. A capability
// without an entry still appears in the catalog using a derived label.
var curatedDescriptions = map[Capability]string{
	CapFinanceWithdrawRead:            "Can view withdrawal requests",
	CapFinanceWithdrawReview:          "Can review, approve, or reject withdrawal requests",
	CapFinanceDisputeResolve:          "Can resolve financial disputes",
	CapFinanceRefundGatewayInitiate:   "Can manually initiate a gateway refund for a refund record",
	CapFinancePaymentMethodView:       "Can view payment methods and their fee configuration",
	CapFinancePaymentMethodManage:     "Can edit payment method fee formulas and channel mapping",
	CapGovernanceDashboardView:        "Can view the admin dashboard",
	CapGovernanceAlertRead:            "Can view platform alerts (system health, SLA, fraud signals)",
	CapGovernanceAlertResolve:         "Can acknowledge, resolve, or dismiss platform alerts",
	CapGovernanceUserRead:             "Can view user details and lists",
	CapGovernanceUserSuspend:          "Can suspend user accounts",
	CapGovernanceUserBan:              "Can ban user accounts",
	CapGovernanceUserActivate:         "Can activate suspended user accounts",
	CapGovernanceUserUnban:            "Can unban a banned user account",
	CapGovernanceRoleAssign:           "Can promote and demote admins (assign roles)",
	CapGovernanceCapabilityAssign:     "Can grant and revoke admin capabilities",
	CapGovernanceAuditRead:            "Can view admin audit logs",
	CapGovernanceAuctionCancel:        "Can emergency-cancel any seller's auction",
	CapModerationCaseRead:             "Can view moderation cases and reports",
	CapModerationContentView:          "Can view reported content",
	CapModerationContentRemove:        "Can remove content",
	CapModerationCaseResolve:          "Can resolve moderation cases",
	CapModerationEvidenceRead:         "Can view original hidden moderation evidence",
	CapModerationAppealRead:           "Can view moderation appeals",
	CapModerationAppealReview:         "Can review and decide moderation appeals",
	CapPromotionExternalProductReview: "Can review external product promotions",
	CapSellerVerificationReview:       "Can review seller verification requests",
	CapSellerSubscriptionRecover:      "Can manually recover a settled subscription payment with no subscription row",
	CapOrderRead:                      "Can view all orders",
	CapConfigView:                     "Can view platform configuration",
	CapConfigUpdateGeneral:            "Can update general platform configuration",
	CapConfigUpdateFinancial:          "Can update financial platform configuration",
	CapSupportTicketRead:              "Can view all support tickets",
	CapSupportTicketRespond:           "Can respond to support tickets",
	CapSupportTicketClaim:             "Can claim support tickets",
	CapSupportTicketResolve:           "Can resolve support tickets",
	CapSupportAdminRead:               "Can view support admin statistics and lists",
	CapSupportTicketEscalate:          "Can escalate support tickets to disputes",
}
