package midtrans

import "testing"

func TestBuildWebhookSignatureRoundTrip(t *testing.T) {
	client := &Client{serverKey: "test-server-key"}
	notification := &NotificationPayload{
		OrderID:     "LAB-SUB-test",
		StatusCode:  "200",
		GrossAmount: "70000.00",
	}

	signature := client.BuildWebhookSignature(notification)
	if signature == "" {
		t.Fatal("BuildWebhookSignature returned an empty signature")
	}

	notification.SignatureKey = signature
	if !client.VerifySignature(notification) {
		t.Fatal("VerifySignature rejected a signature generated by BuildWebhookSignature")
	}
}

func TestAPIError_CreateSnapClassificationMatrix(t *testing.T) {
	tests := []struct {
		name           string
		err            *APIError
		wantClass      SnapCreateErrorClass
		wantDefinitive bool
	}{
		{
			name: "documented_validation_gross_mismatch",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 400,
				Body:       `{"error_messages":["transaction_details.gross_amount is not equal to the sum of item_details"]}`,
			},
			wantClass:      SnapCreateErrorClassDefinitiveNoTransactionCreated,
			wantDefinitive: true,
		},
		{
			name: "documented_validation_invalid_json",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 400,
				Body:       `{"error_messages":["Invalid JSON data provided."]}`,
			},
			wantClass:      SnapCreateErrorClassDefinitiveNoTransactionCreated,
			wantDefinitive: true,
		},
		{
			name: "documented_validation_missing_field",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 400,
				Body:       `{"error_messages":["Missing mandatory field transaction_details.order_id"]}`,
			},
			wantClass:      SnapCreateErrorClassDefinitiveNoTransactionCreated,
			wantDefinitive: true,
		},
		{
			name: "duplicate_order_body_400",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 400,
				Body:       `{"error_messages":["transaction_details.order_id has been paid and utilized, please use another order ID"]}`,
			},
			wantClass:      SnapCreateErrorClassExistingTransactionPossible,
			wantDefinitive: false,
		},
		{
			name: "duplicate_order_status_406",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 406,
				Body:       `{"error_messages":["transaction_details.order_id has been paid and utilized, please use another order ID"]}`,
			},
			wantClass:      SnapCreateErrorClassExistingTransactionPossible,
			wantDefinitive: false,
		},
		{
			name: "unauthorized_401",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 401,
				Body:       `{"error_messages":["Access denied due to unauthorized transaction, please check client or server key"]}`,
			},
			wantClass:      SnapCreateErrorClassConfigurationOrProgrammingError,
			wantDefinitive: false,
		},
		{
			name: "unknown_4xx_429",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 429,
				Body:       `{"error_messages":["too many requests"]}`,
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
		{
			name: "unknown_4xx_404",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 404,
				Body:       `{"error_messages":["resource not found"]}`,
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
		{
			name: "server_error_500",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 500,
				Body:       `{"error_messages":["internal server error"]}`,
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
		{
			name: "server_error_503",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 503,
				Body:       `{"error_messages":["Bank/partner is experiencing connection issue."]}`,
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
		{
			name: "unknown_4xx_body_text",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 412,
				Body:       `{"error_messages":["transaction status cannot be updated"]}`,
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
		{
			name: "empty_body_safe",
			err: &APIError{
				Operation:  "create_snap",
				StatusCode: 418,
				Body:       "",
			},
			wantClass:      SnapCreateErrorClassTransientOrUncertain,
			wantDefinitive: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := tc.err.CreateSnapClassification(); got != tc.wantClass {
				t.Fatalf("CreateSnapClassification() = %q, want %q", got, tc.wantClass)
			}
			if got := tc.err.DefinitiveRefusal(); got != tc.wantDefinitive {
				t.Fatalf("DefinitiveRefusal() = %t, want %t", got, tc.wantDefinitive)
			}
		})
	}
}

func TestAPIError_CreateSnapClassification_DuplicatePrecedenceOverGenericValidation(t *testing.T) {
	err := &APIError{
		Operation:  "create_snap",
		StatusCode: 400,
		Body:       `{"error_messages":["duplicate order id", "validation error"]}`,
	}

	if got := err.CreateSnapClassification(); got != SnapCreateErrorClassExistingTransactionPossible {
		t.Fatalf("CreateSnapClassification() = %q, want %q", got, SnapCreateErrorClassExistingTransactionPossible)
	}
}

func TestAPIError_DefinitiveRefusalRejectsGeneric4xx(t *testing.T) {
	err := &APIError{
		Operation:  "create_snap",
		StatusCode: 403,
		Body:       `{"error_messages":["forbidden"]}`,
	}

	if err.DefinitiveRefusal() {
		t.Fatal("DefinitiveRefusal() returned true for a generic 4xx without definitive no-transaction evidence")
	}
	if got := err.CreateSnapClassification(); got != SnapCreateErrorClassTransientOrUncertain {
		t.Fatalf("CreateSnapClassification() = %q, want %q", got, SnapCreateErrorClassTransientOrUncertain)
	}
}
