#!/bin/bash

echo "========================================"
echo "Deploying Seller Payment Handler Fix"
echo "========================================"
echo ""
echo "This will deploy the fixed cloud function that processes"
echo "seller subscription payments correctly."
echo ""
echo "Bug Fixed: Status mismatch between webhook and handler"
echo "- Webhook creates events with status 'success'"
echo "- Handler now accepts both 'success' and 'paid'"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "Deploying onSellerPaymentEvent function..."
firebase deploy --only functions:onSellerPaymentEvent

echo ""
echo "========================================"
echo "Deployment Complete!"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Run manual fix script for users who already paid:"
echo "   cd functions"
echo "   npx ts-node scripts/fix_seller_payments.ts"
echo ""
echo "2. Test with new payment to verify it works"
echo ""
